### ISSUE TITLE
Could not find a version that satisfies the requirement r2pipe==1.2.0

### ISSUE THREAD

**Issue by r4t31** [danieluhricek/LiSa#16]
Collecting click==7.0
  Downloading Click-7.0-py2.py3-none-any.whl (81 kB)
Collecting disspcap==1.1.1
  Downloading disspcap-1.1.1.tar.gz (19 kB)
Collecting r2pipe==1.2.0
  Downloading r2pipe-1.2.0.tar.gz (8.9 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-s1258syi/r2pipe_d32ff5bfa6174b2fa15dadcc96994aeb/setup.py'"'"'; __file__='"'"'/tmp/pip-install-s1258syi/r2pipe_d32ff5bfa6174b2fa15dadcc96994aeb/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"         cwd: /tmp/pip-install-s1258syi/r2pipe_d32ff5bfa6174b2fa15dadcc96994aeb/
    Complete output (15 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-s1258syi/r2pipe_d32ff5bfa6174b2fa15dadcc96994aeb/setup.py", line 2, in <module>
        import r2pipe
      File "/tmp/pip-install-s1258syi/r2pipe_d32ff5bfa6174b2fa15dadcc96994aeb/r2pipe/__init__.py", line 38, in <module>
        from .open_sync import open
      File "/tmp/pip-install-s1258syi/r2pipe_d32ff5bfa6174b2fa15dadcc96994aeb/r2pipe/open_sync.py", line 14, in <module>
        from .open_base import OpenBase, get_radare_path
      File "/tmp/pip-install-s1258syi/r2pipe_d32ff5bfa6174b2fa15dadcc96994aeb/r2pipe/open_base.py", line 20, in <module>
        from .native import RCore
      File "/tmp/pip-install-s1258syi/r2pipe_d32ff5bfa6174b2fa15dadcc96994aeb/r2pipe/native.py", line 25, in <module>
        lib = CDLL(lib_name)
      File "/usr/local/lib/python3.6/ctypes/__init__.py", line 348, in __init__
        self._handle = _dlopen(self._name, mode)
    OSError: libr_core.so: cannot open shared object file: No such file or directory
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/9d/a7/24bb1567aa171b0dcf76a267281fca60ff4ab60b1107ec4d5808e3d9e617/r2pipe-1.2.0.tar.gz#sha256=445a61c4a4b4fc038355f9a2df48298311150de07f2a949f868aaa142bee43e3 (from https://pypi.org/simple/r2pipe/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement r2pipe==1.2.0
ERROR: No matching distribution found for r2pipe==1.2.0
ERROR: Service 'worker' failed to build : The command '/bin/sh -c pip install -r requirements.txt     && iprange -j data/blacklists/* > data/ipblacklist     && ./docker/worker/maxmind.sh $maxmind_key     && apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false     git     gcc     g++     make     patch     && rm -rf /var/lib/apt/lists/*     && rm -rf /radare2/.git' returned a non-zero code: 1

**Comment by danielpoliakov** [comment]
Solved by #15
