### ISSUE TITLE
Got BrokenPipeError while analyzing binary file

### ISSUE THREAD

**Issue by a798047815** [danieluhricek/LiSa#19]
Hi,
I just installed your LiSa sandbox and I submitted a binary file (I randomly chose '/bin/git' for example), but I got the BrokenPipeError.
The Failure details is as follow:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/lisa/lisa/web_api/tasks.py", line 80, in full_analysis
    master.run()
  File "/home/lisa/lisa/analysis/top_level.py", line 69, in run
    sub_output = analyzer.run_analysis()
  File "/home/lisa/lisa/analysis/static_analysis.py", line 31, in run_analysis
    self._r2.cmd('aaa')
  File "/usr/local/lib/python3.6/site-packages/r2pipe/open_base.py", line 232, in cmd
    res = self._cmd(cmd, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/r2pipe/open_sync.py", line 109, in _cmd_process
    self.process.stdin.write((cmd + "\n").encode("utf8"))
BrokenPipeError: [Errno 32] Broken pipe
```
The docker-compose logs seem normal:
```
nginx_1     | 172.42.0.1 - - [08/May/2021:09:07:13 +0000] "GET /submit HTTP/1.1" 200 2120 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0" "-"
nginx_1     | 172.42.0.1 - - [08/May/2021:09:07:13 +0000] "GET /static/media/logo-dark.011f1691.png HTTP/1.1" 200 21974 "http://localhost:4242/submit" "Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0" "-"
nginx_1     | 172.42.0.1 - - [08/May/2021:09:07:13 +0000] "GET /favicon.ico HTTP/1.1" 200 1086 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0" "-"
nginx_1     | 2021/05/08 09:07:29 [warn] 22#22: *56 a client request body is buffered to a temporary file /var/cache/nginx/client_temp/0000000003, client: 172.42.0.1, server: lisa, request: "POST /api/tasks/create/file HTTP/1.1", host: "localhost:4242", referrer: "http://localhost:4242/submit"
rabbitmq_1  | 2021-05-08 09:07:29.331 [info] <0.1626.0> accepting AMQP connection <0.1626.0> (172.42.0.10:38714 -> 172.42.0.13:5672)
api_1       | 2021-05-08 09:07:29 15:connection [DEBUG] - Start from server, version: 0.9, properties: {'capabilities': {'publisher_confirms': True, 'exchange_exchange_bindings': True, 'basic.nack': True, 'consumer_cancel_notify': True, 'connection.blocked': True, 'consumer_priorities': True, 'authentication_failure_close': True, 'per_consumer_qos': True, 'direct_reply_to': True}, 'cluster_name': 'rabbit@f4304eb61574', 'copyright': 'Copyright (c) 2007-2021 VMware, Inc. or its affiliates.', 'information': 'Licensed under the MPL 2.0. Website: https://rabbitmq.com', 'platform': 'Erlang/OTP 23.3.3', 'product': 'RabbitMQ', 'version': '3.8.16'}, mechanisms: [b'AMQPLAIN', b'PLAIN'], locales: ['en_US']
rabbitmq_1  | 2021-05-08 09:07:29.333 [info] <0.1626.0> connection <0.1626.0> (172.42.0.10:38714 -> 172.42.0.13:5672): user 'lisa' authenticated and granted access to vhost '/'
api_1       | 2021-05-08 09:07:29 15:channel [DEBUG] - using channel_id: 1
api_1       | 2021-05-08 09:07:29 15:channel [DEBUG] - Channel open
api_1       | [pid: 15|app: 0|req: 5/18] 172.42.0.1 () {46 vars in 856 bytes} [Sat May  8 09:07:29 2021] POST /api/tasks/create/file => generated 51 bytes in 60 msecs (HTTP/1.1 200) 4 headers in 137 bytes (3 switches on core 0)
worker_1    | 2021-05-08 09:07:29 18:strategy [INFO] - Received task: lisa.web_api.tasks.full_analysis[4c8ff487-6156-4477-8a91-c8f29fac1be9]  
nginx_1     | 172.42.0.1 - - [08/May/2021:09:07:29 +0000] "POST /api/tasks/create/file HTTP/1.1" 200 51 "http://localhost:4242/submit" "Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0" "-"
nginx_1     | 172.42.0.1 - - [08/May/2021:09:07:40 +0000] "GET /api/tasks/failed HTTP/1.1" 200 14154 "http://localhost:4242/failed" "Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0" "-"
api_1       | [pid: 15|app: 0|req: 6/19] 172.42.0.1 () {40 vars in 581 bytes} [Sat May  8 09:07:40 2021] GET /api/tasks/failed => generated 14154 bytes in 5 msecs (HTTP/1.1 200) 3 headers in 106 bytes (1 switches on core 0)
rabbitmq_1  | 2021-05-08 09:10:29.351 [error] <0.1626.0> closing AMQP connection <0.1626.0> (172.42.0.10:38714 -> 172.42.0.13:5672):
rabbitmq_1  | missed heartbeats from client, timeout: 60s
rabbitmq_1  | 2021-05-08 09:10:29.352 [info] <0.1677.0> Closing all channels from connection '172.42.0.10:38714 -> 172.42.0.13:5672' because it has been closed
```
Is there anything I can do to fix it?
I'm using CentOS 8.3

**Comment by a798047815** [comment]
I reinstalled it and it just worked pretty well. Maybe there is something wrong in my previous pipeline setting.
