### ISSUE TITLE
Consistently getting  KeyError: 'minopsz'

### ISSUE THREAD

**Issue by xxdesmus** [danieluhricek/LiSa#21]
Hi there,

Thank you for sharing this amazing project. I set things up, and when I try to analyze any sample I always get the same KeyError: 'minopsz' error.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 405, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 697, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/lisa/lisa/web_api/tasks.py", line 80, in full_analysis
    master.run()
  File "/home/lisa/lisa/analysis/top_level.py", line 69, in run
    sub_output = analyzer.run_analysis()
  File "/home/lisa/lisa/analysis/static_analysis.py", line 34, in run_analysis
    self._r2_info()
  File "/home/lisa/lisa/analysis/static_analysis.py", line 62, in _r2_info
    'min_opsize': info['bin']['minopsz'],
KeyError: 'minopsz'
```

am I missing something obvious?

**Comment by AlbertoFDR** [comment]
Hi, I think that's because r2 last version has change the data structure of the command. 

In the next photo you can see that "minopsz" is now part of 'core' and not 'bin':
![screen1](https://user-images.githubusercontent.com/21290259/131213886-8179b91f-7485-4090-9c77-a1b1cae3336f.png)

One possible solution inside lisa/analysis/static_analysis.py (I don't know 100% if works 😊):
![screen2](https://user-images.githubusercontent.com/21290259/131213895-8356a9e3-1d83-40bd-874b-9f59410e7e54.png)

**Comment by StarrySai** [comment]
> Hi, I think that's because r2 last version has change the data structure of the command.
> 
> In the next photo you can see that "minopsz" is now part of 'core' and not 'bin':
> ![screen1](https://user-images.githubusercontent.com/21290259/131213886-8179b91f-7485-4090-9c77-a1b1cae3336f.png)
> 
> One possible solution inside lisa/analysis/static_analysis.py (I don't know 100% if works 😊):
> ![screen2](https://user-images.githubusercontent.com/21290259/131213895-8356a9e3-1d83-40bd-874b-9f59410e7e54.png)

Does your sandbox work?
After I changed 'bin' to 'core', the sandbox was able to upload the binaries successfully, but never analyzed it.

![image](https://user-images.githubusercontent.com/46144833/133569411-bef8957a-58aa-47f1-95ca-e35a2568242a.png)

The pcap file can be analyzed normally.
 Can you help me? Thanks.

**Comment by inshaltahir** [comment]
currently having the same issue. I tried the solution mentioned here but its not working. The "Key Error: minopsz" is gone but I see no analysis on the web interface and no report is generated for the sample.

**Comment by evlp** [comment]
Yep same here

**Comment by xchaoinfo** [comment]
https://github.com/danieluhricek/LiSa/blob/897fc5133e368273f5fd78339f72a5c3c1e490ce/lisa/analysis/static_analysis.py#L30
drop `["-2"]`  and with @AlbertoFDR solution.

it works.
radare2 v5.5.0

**Comment by inshaltahir** [comment]
Oh this actually worked. Thank You so much.

**Comment by jrespeto** [comment]
https://github.com/danieluhricek/LiSa/pull/30

**Comment by cnagavenkat** [comment]
I'm still facing KeyError: 'minopsz' , after modifying the "static_analysis.py" with the mentioned changes. what else am I missing, can someone help me in resolving this issue?
![image](https://user-images.githubusercontent.com/63532383/208108872-45d6c44c-8965-4896-8dd0-e7cbd3437250.png)
![image](https://user-images.githubusercontent.com/63532383/208111689-52491db6-2550-4ff2-ac8a-8682e1d2a111.png)

**Comment by marugish** [comment]
> I'm still facing KeyError: 'minopsz' , after modifying the "static_analysis.py" with the mentioned changes. what else am I missing, can someone help me in resolving this issue? ![image](https://user-images.githubusercontent.com/63532383/208108872-45d6c44c-8965-4896-8dd0-e7cbd3437250.png) ![image](https://user-images.githubusercontent.com/63532383/208111689-52491db6-2550-4ff2-ac8a-8682e1d2a111.png)

Hi! Did you manage to fix this error?

**Comment by mikereiter** [comment]
Also having this problem, please help
