### ISSUE TITLE
Failed task

### ISSUE THREAD

**Issue by mperov** [danieluhricek/LiSa#37]
I could run LiSa, but when I submitted my file I got:
```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 450, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 731, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/lisa/lisa/web_api/tasks.py", line 80, in full_analysis
    master.run()
  File "/home/lisa/lisa/analysis/top_level.py", line 69, in run
    sub_output = analyzer.run_analysis()
  File "/home/lisa/lisa/analysis/static_analysis.py", line 34, in run_analysis
    self._r2_info()
  File "/home/lisa/lisa/analysis/static_analysis.py", line 62, in _r2_info
    'min_opsize': info['bin']['minopsz'],
KeyError: 'minopsz'
```

I attached screen picture:
![failed_task](https://user-images.githubusercontent.com/4026525/206726930-f38c440e-4ae0-426d-aca5-705c0ec3ca4b.png)

**Comment by mperov** [comment]
I suppose that version radare2 is changed, because in console of built container I got:
```console
root@4fc43691f54f:~# rabin2 -I /bin/ls
arch     x86
baddr    0x0
binsz    145252
bintype  elf
bits     64
canary   true
class    ELF64
crypto   false
endian   little
havecode true
intrp    /lib64/ld-linux-x86-64.so.2
laddr    0x0
lang     c
linenum  false
lsyms    false
machine  AMD x86-64 architecture
nx       true
os       linux
pic      true
relocs   false
relro    partial
rpath    NONE
sanitize false
static   false
stripped true
subsys   linux
va       true
```

As you can see there aren't minopsz and maxopsz parameters.

I will try remove getting these.

**Comment by mperov** [comment]
I fixed it. See please [my PR](https://github.com/danieluhricek/LiSa/pull/36)
